### ISSUE TITLE
Restriction for question and items names

### ISSUE THREAD

**Issue by mhebing** [paneldata/soep-is#12]
@kwenzig Ich glaube, es wäre gut, wenn wir auch für die Namen von Fragen und Items gewissen Regeln hätten. Hab gerade IS importiert und Punkte (z.B. "Q31.1") sind ziemlich unelegant für 'ne ordentliche API. Da könnte man doch sicher auch "Q13_1" nehmen, oder?

**Comment by kwenzig** [comment]
Wo keine Regeln, da Wildwuchs. Wobei underscore in der Darstellung (Web/PDF) m.E. nicht so schön ausschaut.

**Comment by afuetterer** [comment]
Can this issue be closed?
