### ISSUE TITLE
Provide additional metadata files

### ISSUE THREAD

**Issue by afuetterer** [paneldata/soep-is#35]
- [x] analysis_units.csv
    - example: [analysis_units.csv](https://github.com/paneldata/soep-is/blob/6a2bb4212cc11bd9e0c67e45ed04e29a41fada57/metadata/analysis_units.csv)
- [x] conceptual_datasets.csv
    - example: [conceptual_datasets.csv](https://github.com/paneldata/soep-is/blob/0bc5a1e37e2ca07f17d1eba91e09c38b749ac727/metadata/conceptual_datasets.csv)
- [x] periods.csv
    - example: [periods.csv](https://github.com/paneldata/soep-is/blob/bb31e5e95f913516b39ab5479e889111ce5b14e0/metadata/periods.csv)

Marcel's documentation:
- https://github.com/mhebing/ddionrails2/blob/master/docs/datamodel/output/analysis_unit.rst
- https://github.com/mhebing/ddionrails2/blob/master/docs/datamodel/output/conceptual_dataset.rst
- https://github.com/mhebing/ddionrails2/blob/master/docs/datamodel/output/period.rst

**Comment by kwenzig** [comment]
Will be available in next pull request
