### ISSUE TITLE
Provide a "datasets.csv" file

### ISSUE THREAD

**Issue by afuetterer** [paneldata/soep-is#36]
Please provide a file called "datasets.csv" containing the following columns:

- study_name (mandatory, will be validated against: "soep-is")
- name (mandatory, must be unique)
- label (mandatory, must be unique)
- description (optional?)
- conceptual_dataset_name
- analysis_unit_name
- period_name
- label_de?

I just had a look at this:
- https://github.com/mhebing/ddionrails2/blob/master/docs/datamodel/input/dataset.rst
- https://github.com/mhebing/ddionrails2/blob/master/docs/datamodel/output/dataset.rst

Please include only datasets for publication on paneldata.org.

I merged `logical_datasets.csv` and `datasets_distributions.csv` to achieve this.

See example:
https://github.com/paneldata/soep-is/blob/3a61a3beaa54720399665477a40465888afb01d9/metadata/datasets.csv
~https://github.com/paneldata/soep-is/blob/1b11f4b5aa2fd244a41e7030782122be2bdc7690/metadata/datasets.csv~

Please remove `logical_datasets.csv`, `datasets_distributions.csv` and `distributions.csv` from your delivery as they are not imported into paneldata.org at the moment.

**Comment by kwenzig** [comment]
dataset.csv will be available with next pull request and files will be deleted.
