### ISSUE TITLE
Provide a "variables.csv" file

### ISSUE THREAD

**Issue by afuetterer** [paneldata/soep-is#38]
At the moment it is hard to say many variables are part of SOEP-IS 2016.2.

If I take the variables from the XML files, there is no way to validate if they are "complete". The XML files do not contain concepts information. see #37 

Please provide a file called "variables.csv" containing the following columns:
- name (mandatory)
- dataset_name  (mandatory, will be validated against datasets.csv)
- study_name  (mandatory, will be validated against: "soep-is")
- label (mandatory)
- label_de (mandatory)
- description

see also:
https://github.com/mhebing/ddionrails2/blob/master/docs/datamodel/output/variable.rst

Please include only variables from datasets for publication on paneldata.org.

**Comment by kwenzig** [comment]
Some sort of variables will be included in next pull request.
