### ISSUE TITLE
SOEP-IS 2014.1

### ISSUE THREAD

**Issue by mhebing** [paneldata/soep-is#9]
- [x] Run r2ddi for v2014.1.
- [ ] Do we have release notes? If so, add them to the metadata for import.
## Missing datasets
- [x] hbrutto
- [x] inno
- [x] pbrutto
## Questions

@kwenzig The metadata for SOEP-IS are already prepared for version 2014.1, correct?

**Comment by kwenzig** [comment]
They are, but version number is 2014.

**Comment by mhebing** [comment]
@kwenzig @jgoebel Do we all agree to always document the latest version of the data but without an explicit reference to the bugfix (e.g., v2014.1 as v2014). Or should we document the v2014 and v2014.1 separately?

**Comment by kwenzig** [comment]
The cost of managing a completely new version (introduce a row in generations for each variable in each dataset) seem to be higher than to loose prior-bugfix-information.

**Comment by mhebing** [comment]
Do we have release notes for v2014 and v2014.1, which would document the changes?

**Comment by mhebing** [comment]
r2ddi was not able to parse the following three datasets:

- hbrutto
- inno
- pbrutto

Error:

```
[1] "Error in names(attr(read_dta, \"label.table\")[[x]]) <- .encconv(names(attr(read_dta,  : \n  Versuch ein Attribut von NULL zu setzen\n"
attr(,"class")
[1] "try-error"
attr(,"condition")
<simpleError in names(attr(read_dta, "label.table")[[x]]) <- .encconv(names(attr(read_dta,     "label.table")[[x]])): Versuch ein Attribut von NULL zu setzen>
```

@kwenzig Looks like there are errors in the (value) labels for these three datasets in Stata.

**Comment by mhebing** [comment]
Weird thing: I got 4 errors but only three datasets seem to be missing…

**Comment by kwenzig** [comment]
```
. use "S:\DATA2\SOEP-IS\SOEP-IS_2014.1_release\download\soep-is.2014.1_stata_en\hbrutto.dta" , clear
(DIW-SOEP, SOEP-IS 2014.1 (en), doi:10.5684/soep.is.2014.1)

. labundef
2 undefined value labels
syear (syear)
hpmax (hpmax)
```

**Comment by mhebing** [comment]
Datasets fixed and prepared by r2ddi.
